#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OXCoder.DBModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oxcoderdb")]
	public partial class OXChallengeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertox_challenge(ox_challenge instance);
    partial void Updateox_challenge(ox_challenge instance);
    partial void Deleteox_challenge(ox_challenge instance);
    #endregion
		
		public OXChallengeDataContext() : 
				base(global::OXCoder.DBModel.Properties.Settings.Default.oxcoderdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OXChallengeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXChallengeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXChallengeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXChallengeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ox_challenge> ox_challenge
		{
			get
			{
				return this.GetTable<ox_challenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ox_challenge")]
	public partial class ox_challenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _challengeid;
		
		private int _companyid;
		
		private string _challengename;
		
		private System.Nullable<System.DateTime> _begintime;
		
		private System.Nullable<System.DateTime> _endtime;
		
		private string _tags;
		
		private System.Nullable<int> _challengelevel;
		
		private System.Nullable<int> _photo;
		
		private System.Nullable<int> _publicorprivate;
		
		private string _salary;
		
		private System.Nullable<int> _codernum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnchallengeidChanging(string value);
    partial void OnchallengeidChanged();
    partial void OncompanyidChanging(int value);
    partial void OncompanyidChanged();
    partial void OnchallengenameChanging(string value);
    partial void OnchallengenameChanged();
    partial void OnbegintimeChanging(System.Nullable<System.DateTime> value);
    partial void OnbegintimeChanged();
    partial void OnendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnendtimeChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OnchallengelevelChanging(System.Nullable<int> value);
    partial void OnchallengelevelChanged();
    partial void OnphotoChanging(System.Nullable<int> value);
    partial void OnphotoChanged();
    partial void OnpublicorprivateChanging(System.Nullable<int> value);
    partial void OnpublicorprivateChanged();
    partial void OnsalaryChanging(string value);
    partial void OnsalaryChanged();
    partial void OncodernumChanging(System.Nullable<int> value);
    partial void OncodernumChanged();
    #endregion
		
		public ox_challenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid", DbType="NChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string challengeid
		{
			get
			{
				return this._challengeid;
			}
			set
			{
				if ((this._challengeid != value))
				{
					this.OnchallengeidChanging(value);
					this.SendPropertyChanging();
					this._challengeid = value;
					this.SendPropertyChanged("challengeid");
					this.OnchallengeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyid", DbType="Int NOT NULL")]
		public int companyid
		{
			get
			{
				return this._companyid;
			}
			set
			{
				if ((this._companyid != value))
				{
					this.OncompanyidChanging(value);
					this.SendPropertyChanging();
					this._companyid = value;
					this.SendPropertyChanged("companyid");
					this.OncompanyidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename", DbType="NVarChar(255)")]
		public string challengename
		{
			get
			{
				return this._challengename;
			}
			set
			{
				if ((this._challengename != value))
				{
					this.OnchallengenameChanging(value);
					this.SendPropertyChanging();
					this._challengename = value;
					this.SendPropertyChanged("challengename");
					this.OnchallengenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begintime", DbType="DateTime")]
		public System.Nullable<System.DateTime> begintime
		{
			get
			{
				return this._begintime;
			}
			set
			{
				if ((this._begintime != value))
				{
					this.OnbegintimeChanging(value);
					this.SendPropertyChanging();
					this._begintime = value;
					this.SendPropertyChanged("begintime");
					this.OnbegintimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> endtime
		{
			get
			{
				return this._endtime;
			}
			set
			{
				if ((this._endtime != value))
				{
					this.OnendtimeChanging(value);
					this.SendPropertyChanging();
					this._endtime = value;
					this.SendPropertyChanged("endtime");
					this.OnendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(255)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengelevel", DbType="Int")]
		public System.Nullable<int> challengelevel
		{
			get
			{
				return this._challengelevel;
			}
			set
			{
				if ((this._challengelevel != value))
				{
					this.OnchallengelevelChanging(value);
					this.SendPropertyChanging();
					this._challengelevel = value;
					this.SendPropertyChanged("challengelevel");
					this.OnchallengelevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="Int")]
		public System.Nullable<int> photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publicorprivate", DbType="Int")]
		public System.Nullable<int> publicorprivate
		{
			get
			{
				return this._publicorprivate;
			}
			set
			{
				if ((this._publicorprivate != value))
				{
					this.OnpublicorprivateChanging(value);
					this.SendPropertyChanging();
					this._publicorprivate = value;
					this.SendPropertyChanged("publicorprivate");
					this.OnpublicorprivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="NVarChar(255)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codernum", DbType="Int")]
		public System.Nullable<int> codernum
		{
			get
			{
				return this._codernum;
			}
			set
			{
				if ((this._codernum != value))
				{
					this.OncodernumChanging(value);
					this.SendPropertyChanging();
					this._codernum = value;
					this.SendPropertyChanged("codernum");
					this.OncodernumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
