#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OXCoder.DBModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oxcoderdb")]
	public partial class OXProjectChallengeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertox_project_challenge(ox_project_challenge instance);
    partial void Updateox_project_challenge(ox_project_challenge instance);
    partial void Deleteox_project_challenge(ox_project_challenge instance);
    #endregion
		
		public OXProjectChallengeDataContext() : 
				base(global::OXCoder.DBModel.Properties.Settings.Default.oxcoderdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OXProjectChallengeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXProjectChallengeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXProjectChallengeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OXProjectChallengeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ox_project_challenge> ox_project_challenge
		{
			get
			{
				return this.GetTable<ox_project_challenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ox_project_challenge")]
	public partial class ox_project_challenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _projectid;
		
		private string _challengeid;
		
		private int _pcid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnprojectidChanging(string value);
    partial void OnprojectidChanged();
    partial void OnchallengeidChanging(string value);
    partial void OnchallengeidChanged();
    partial void OnpcidChanging(int value);
    partial void OnpcidChanged();
    #endregion
		
		public ox_project_challenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectid", DbType="NChar(36)")]
		public string projectid
		{
			get
			{
				return this._projectid;
			}
			set
			{
				if ((this._projectid != value))
				{
					this.OnprojectidChanging(value);
					this.SendPropertyChanging();
					this._projectid = value;
					this.SendPropertyChanged("projectid");
					this.OnprojectidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid", DbType="NChar(36)")]
		public string challengeid
		{
			get
			{
				return this._challengeid;
			}
			set
			{
				if ((this._challengeid != value))
				{
					this.OnchallengeidChanging(value);
					this.SendPropertyChanging();
					this._challengeid = value;
					this.SendPropertyChanged("challengeid");
					this.OnchallengeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pcid
		{
			get
			{
				return this._pcid;
			}
			set
			{
				if ((this._pcid != value))
				{
					this.OnpcidChanging(value);
					this.SendPropertyChanging();
					this._pcid = value;
					this.SendPropertyChanged("pcid");
					this.OnpcidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
